android.useAndroidX=true
android.nonTransitiveRClass=true

org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

kotlin.code.style=official
kotlin.incremental=true

# KSP incremental (KSP2 uses this)
ksp.incremental=true
